//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUserManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class userInformation
    {
        public int id { get; set; }
        [DisplayName("User Name")]
        public string fullName { get; set; }
        public int age { get; set; }
        public string email { get; set; }
        [DisplayName("User Image")]
        public string image { get; set; }
    }
}
