//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUserManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class userLogin
    {
        public int id { get; set; }
        [Required]
        [DisplayName("User Name")]
        public string uName { get; set; }
        [Required]
        
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }
}
